from subprocess import Popen,PIPE
import sys


fi='/home/rubbernecker/ifuzzer_s/Bugs/1_.js'
interpreter_Shell=[]
cmd=["node"]
cmd.append("jsdelta/delta.js")
cmd.append("--cmd")
runcmd='/home/rubbernecker/jsengines/firefox/js/src/build1/dist/bin/js --fuzzing-safe -f /home/rubbernecker/jsengines/firefox/js/src/tests/test262/intl402/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/shell/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_2/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/supporting/test262-shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/supporting/test402-shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_7/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_7/TypedObject/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_6/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8_5/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8_5/reflect-parse/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8_5/extensions/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma/Date/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_5/Expressions/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_5/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_5/JSON/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_5/RegExp/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_7/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8_1/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8_1/strict/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8_1/jit/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_2/version120/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/Class/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/Math/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/LexicalEnvironment/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/Reflect/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/TemplateStrings/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/extensions/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/TypedArray/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/Generators/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/String/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_3/Object/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_3/extensions/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_3/RegExp/shell.js -f'
cmd.append(runcmd)
cmd.append(fi)
p = Popen(cmd, stdout=PIPE,stderr=PIPE)
out, err = p.communicate()
print out
print err
sys.stdout.flush()
sys.stderr.flush()


# ['node', 'codegen/jsdelta/delta.js', '--cmd',, '/tmp/tmplJRP17']
# ['node', 'codegen/jsdelta/delta.js', '--cmd', '/home/rubbernecker/jsengines/firefox/js/src/build1/dist/bin/js --ion-eager --ion-offthread-compile=off --fuzzing-safe -f /home/rubbernecker/jsengines/firefox/js/src/tests/test262/intl402/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/shell/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_2/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/supporting/test262-shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/supporting/test402-shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_7/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_7/TypedObject/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_6/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8_5/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8_5/reflect-parse/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8_5/extensions/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma/Date/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_5/Expressions/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_5/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_5/JSON/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_5/RegExp/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_7/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8_1/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8_1/strict/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_8_1/jit/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/js1_2/version120/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/Class/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/Math/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/LexicalEnvironment/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/Reflect/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/TemplateStrings/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/extensions/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/TypedArray/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/Generators/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_6/String/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_3/Object/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_3/extensions/shell.js -f /home/rubbernecker/jsengines/firefox/js/src/tests/ecma_3/RegExp/shell.js -f', '/tmp/tmplJRP17']
